from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from src.document_processor import DocumentProcessor
from src.dual_model_pipeline import DualModelPipeline
from src.output_writer import OutputWriter
from src.property_range_extractor import PropertyRangeExtractor
from src.rag_context import RagContext
from src.review_engine import ReviewEngine
from src.utils import collect_input_files, ensure_dir, load_config, save_json


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Standard document extraction and review pipeline")
    parser.add_argument("--config", default="config.yaml", help="Path to config.yaml")
    parser.add_argument("--input", default="", help="Override single input file")
    parser.add_argument("--input-dir", default="", help="Override batch input directory")
    parser.add_argument("--output-dir", default="", help="Override output directory")
    parser.add_argument("--raw-document", default="", help="Use one existing raw_document.json and skip OCR")
    parser.add_argument("--raw-document-manifest", default="", help="Use ocr_manifest.json generated by scripts/ocr_only.py")
    parser.add_argument("--raw-document-dir", default="", help="Find */raw_document.json under this directory")
    parser.add_argument("--skip-model-calls", action="store_true", help="Create templates without calling model APIs")
    return parser.parse_args()


def run() -> None:
    args = parse_args()
    config = load_config(Path(args.config))

    if args.input:
        config.setdefault("input", {})["file_path"] = args.input
    if args.input_dir:
        config.setdefault("input", {})["input_dir"] = args.input_dir
    if args.output_dir:
        config.setdefault("input", {})["output_dir"] = args.output_dir
    if args.skip_model_calls:
        config.setdefault("runtime", {})["skip_model_calls"] = True

    output_dir = ensure_dir(config.get("input", {}).get("output_dir", "output"))

    if args.raw_document_manifest:
        manifest = json.loads(Path(args.raw_document_manifest).read_text(encoding="utf-8"))
        for item in manifest:
            raw_document_path = Path(item["raw_document"])
            document = load_raw_document(raw_document_path)
            input_file = resolve_input_file_for_document(document, item.get("input_file", ""))
            run_dir = ensure_dir(output_dir / input_file.stem)
            process_document(config, document, input_file, run_dir)
            print(f"[done] raw_document -> {run_dir}")
        return

    if args.raw_document_dir:
        raw_root = Path(args.raw_document_dir)
        raw_paths = sorted(raw_root.glob("*/raw_document.json"))
        if not raw_paths:
            raise FileNotFoundError(f"No raw_document.json found under {raw_root}")
        for raw_document_path in raw_paths:
            document = load_raw_document(raw_document_path)
            input_file = resolve_input_file_for_document(document, "")
            run_dir = ensure_dir(output_dir / input_file.stem)
            process_document(config, document, input_file, run_dir)
            print(f"[done] raw_document -> {run_dir}")
        return

    if args.raw_document:
        raw_document_path = Path(args.raw_document)
        document = load_raw_document(raw_document_path)
        input_file = resolve_input_file_for_document(document, args.input)
        run_dir = ensure_dir(output_dir / input_file.stem)
        process_document(config, document, input_file, run_dir)
        print(f"[done] raw_document -> {run_dir}")
        return

    files = collect_input_files(config)
    if not files:
        raise FileNotFoundError("No input files found. Check input.file_path or input.input_dir in config.yaml.")

    processor = DocumentProcessor(config)
    for input_file in files:
        print(f"[start] {input_file}")
        run_dir = ensure_dir(output_dir / input_file.stem)
        document = processor.process(input_file)
        process_document(config, document, input_file, run_dir)
        print(f"[done] {input_file} -> {run_dir}")


def process_document(config: dict, document: dict, input_file: Path, run_dir: Path) -> None:
    if config.get("output", {}).get("save_raw_document", True):
        save_json(run_dir / "raw_document.json", document)

    rag = RagContext(config)
    pipeline = DualModelPipeline(config)
    reviewer = ReviewEngine(config)
    writer = OutputWriter(config)

    chunks = rag.build_chunks(document)
    if config.get("output", {}).get("save_chunks", True):
        save_json(run_dir / "chunks.json", [chunk.to_dict() for chunk in chunks])

    model_outputs = pipeline.extract(document, chunks)
    if config.get("output", {}).get("save_model_json", True):
        save_json(run_dir / "model_outputs.json", model_outputs)

    comparison = reviewer.compare(model_outputs)
    review_rows = reviewer.build_manual_review(comparison, chunks, rag)
    final_rows = reviewer.build_final_rows(model_outputs, comparison, review_rows)
    general_row = infer_general_row(document, first_general_row(final_rows), input_file)
    property_rows = PropertyRangeExtractor(config).extract(document, general_row)
    if property_rows:
        final_rows = property_rows
        if config.get("output", {}).get("save_model_json", True):
            save_json(run_dir / "property_range_rows.json", property_rows)
    writer.write_all(run_dir, input_file, document, chunks, model_outputs, comparison, review_rows, final_rows)


def first_general_row(rows: list[dict]) -> dict:
    return rows[0] if rows else {}


def infer_general_row(document: dict, row: dict, input_file: Path) -> dict:
    result = dict(row or {})
    text = "\n".join(str(page.get("text", "")) for page in document.get("pages", [])[:3])
    source = " ".join([str(document.get("file_name") or ""), str(document.get("source_file") or ""), str(input_file)])

    if not clean_general_value(result.get("规范号")):
        result["规范号"] = infer_standard_number(text + "\n" + source) or "无"
    if not clean_general_value(result.get("规范版本")):
        result["规范版本"] = "无"
    if not clean_general_value(result.get("规范年代")):
        result["规范年代"] = infer_year(result.get("规范号", "") + "\n" + text + "\n" + source) or "无"
    if not clean_general_value(result.get("材料类型")):
        result["材料类型"] = infer_material_type(text) or "无"
    if not clean_general_value(result.get("规范名称")):
        result["规范名称"] = infer_standard_name(text) or "无"
    if not clean_general_value(result.get("应用场景")):
        result["应用场景"] = infer_application_scene(text) or "无"
    return result


def clean_general_value(value: object) -> str:
    text = str(value or "").strip()
    return "" if text in {"", "null", "None", "无"} else text


def infer_standard_number(text: str) -> str:
    normalized = text.replace("+", " ").replace("_", " ").replace("—", "-")
    match = re.search(r"\bGB\s*/?\s*T\s*([0-9]+(?:\.[0-9]+)?)\s*[-－]\s*(20\d{2}|19\d{2})\b", normalized, re.I)
    if match:
        return f"GB/T {match.group(1)}-{match.group(2)}"
    match = re.search(r"\bGBT\s*([0-9]+(?:\.[0-9]+)?)\s*[-－]\s*(20\d{2}|19\d{2})\b", normalized, re.I)
    if match:
        return f"GB/T {match.group(1)}-{match.group(2)}"
    match = re.search(r"\bGB\s*([0-9]+(?:\.[0-9]+)?)\s*[-－]\s*(20\d{2}|19\d{2})\b", normalized, re.I)
    if match:
        return f"GB {match.group(1)}-{match.group(2)}"
    return ""


def infer_year(text: str) -> str:
    match = re.search(r"(20\d{2}|19\d{2})", str(text or ""))
    return match.group(1) if match else ""


def infer_material_type(text: str) -> str:
    if "铝" in text and "合金" in text:
        return "铝及铝合金"
    if "钢" in text:
        return "钢"
    return ""


def infer_standard_name(text: str) -> str:
    lines = [line.strip() for line in str(text or "").splitlines() if line.strip()]
    start = -1
    for index, line in enumerate(lines):
        if re.search(r"\bGB\s*/?\s*T\b|\bGBT\b|\bGB\b", line, re.I):
            start = index + 1
            break
    if start < 0:
        return ""
    title_lines: list[str] = []
    for line in lines[start : start + 8]:
        if any(stop in line for stop in ("发布", "实施", "国家市场", "标准化")):
            break
        if "代替" in line or re.fullmatch(r"SAC|ICS.*|CCS.*", line, re.I):
            continue
        if re.search(r"[A-Za-z]", line) and not re.search(r"[\u4e00-\u9fff]", line):
            title_lines.append(line)
            continue
        if re.search(r"[\u4e00-\u9fff]", line) and not re.search(r"^(SAC|ICS|CCS)", line, re.I):
            title_lines.append(line)
    return "\n".join(title_lines).strip()


def infer_application_scene(text: str) -> str:
    compact = re.sub(r"\s+", "", str(text or ""))
    match = re.search(r"(本(?:文件|标准)适用于[^。；;]{8,120}[。；;]?)", compact)
    return match.group(1) if match else ""


def load_raw_document(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def resolve_input_file_for_document(document: dict, input_override: str = "") -> Path:
    if input_override:
        return Path(input_override)
    source_file = document.get("source_file") or document.get("file_name") or "document.pdf"
    return Path(source_file)


if __name__ == "__main__":
    run()
